### ISSUE TITLE
`oc enable` fails to find tar files

### ISSUE THREAD

**Issue by rhagarty** [cloud-native-toolkit/ibm-garage-cloud-cli#118]
I installed the latest version of the CLI (1.16.4), and am getting `TAR_BAD_ARCHIVE` error.

For stack trace, pls see https://ibm-cloudplatform.slack.com/archives/CPJDVFAN8/p1617033769062700

**Comment by bwoolf1** [comment]
New failure with the `igc enable` command (in IGC v1.16.4). The tar file(s) for the pipelines seems to be missing:

```
$ igc --version
1.16.4

$  temp igc enable
Looking up pipelines from repository: https://cloud-native-toolkit.github.io/garage-pipelines/
? Which pipeline should be enabled? nodejs
piping stream
**Here's what happened**
1. A listing of available pipelines was retrieved from https://cloud-native-toolkit.github.io/garage-pipelines/
2. You selected the stable/nodejs@latest pipeline
No files were changed in your repo
node:events:355
      throw er; // Unhandled 'error' event
      ^
Error: TAR_BAD_ARCHIVE: Unrecognized archive format
    at Unpack.warn (/Users/bwoolf/.npm/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/node_modules/tar/lib/warn-mixin.js:19:40)
    at Unpack.warn (/Users/bwoolf/.npm/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/node_modules/tar/lib/unpack.js:189:18)
    at Unpack.<anonymous> (/Users/bwoolf/.npm/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/node_modules/tar/lib/parse.js:81:14)
    at Unpack.emit (node:events:390:22)
    at Unpack.[emit] (/Users/bwoolf/.npm/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/node_modules/tar/lib/parse.js:285:12)
    at Unpack.[maybeEnd] (/Users/bwoolf/.npm/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/node_modules/tar/lib/parse.js:401:17)
    at Unpack.[consumeChunk] (/Users/bwoolf/.npm/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/node_modules/tar/lib/parse.js:432:21)
    at Unpack.write (/Users/bwoolf/.npm/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/node_modules/tar/lib/parse.js:364:25)
    at Unpack.end (/Users/bwoolf/.npm/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/node_modules/tar/lib/parse.js:477:14)
    at Unzip.onend (node:internal/streams/readable:689:10)
Emitted 'error' event on Unpack instance at:
    at Unpack.onerror (node:internal/streams/readable:769:14)
    at Unpack.emit (node:events:378:20)
    at Unpack.warn (/Users/bwoolf/.npm/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/node_modules/tar/lib/warn-mixin.js:19:12)
    at Unpack.warn (/Users/bwoolf/.npm/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/node_modules/tar/lib/unpack.js:189:18)
    [... lines matching original stack trace ...]
    at Unpack.write (/Users/bwoolf/.npm/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/node_modules/tar/lib/parse.js:364:25) {
  recoverable: false,
  cwd: '/Users/bwoolf/dev/git/temp/tmp.enable',
  code: 'TAR_BAD_ARCHIVE',
  tarCode: 'TAR_BAD_ARCHIVE'
}
```

Same error with any pipeline: `nodejs`, `java-maven`, and `java-gradle`.

**Comment by bwoolf1** [comment]
Looks like it's working now:

```
$ igc --version
1.16.4
$ ls -l
$ igc enable
Looking up pipelines from repository: https://cloud-native-toolkit.github.io/garage-pipelines/
? Which pipeline should be enabled? java-maven
piping stream
**Here's what happened**

1. A listing of available pipelines was retrieved from https://cloud-native-toolkit.github.io/garage-pipelines/
2. You selected the stable/java-maven@latest pipeline
3. We added the following files to your repo:
  - Jenkinsfile
  - chart
  - pipeline.yaml
  - sonar-project.properties

Don't forget to commit the new files
$ ls -l
total 56
-rw-r--r--  1 bwoolf  staff  19434 Mar 30 13:58 Jenkinsfile
drwxr-xr-x  3 bwoolf  staff     96 Mar 30 13:58 chart
-rw-r--r--  1 bwoolf  staff     64 Mar 30 13:58 pipeline.yaml
-rw-r--r--  1 bwoolf  staff     64 Mar 30 13:58 sonar-project.properties
```
